@include('front-end.header')
 <style>

        .privacy {
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        h1 {
            margin: 0;
            font-size: 28px;
        }
        h2 {
            color: #2c3e50;
            border-bottom: 2px solid #eaeaea;
            padding-bottom: 5px;
            margin-top: 30px;
        }
        h3 {
            color: #3498db;
        }
        .last-updated {
            font-style: italic;
            color: #7f8c8d;
        }
        .section {
            background-color: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .contact-info {
            background-color: #e8f4fc;
            padding: 15px;
            border-left: 4px solid #3498db;
        }
        ul {
            padding-left: 20px;
        }
        li {
            margin-bottom: 10px;
        }
    </style>
    
     <header class="privacy">
        <h1>Privacy Policy</h1>
        <!--<div class="last-updated">Last updated: April 14, 2025</div>-->
    </header>
 <div class="section">
        <h2>Introduction</h2>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
</p>
        
    </div>

    <div class="section">
        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h3>Definitions</h3>
       <ul>
    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Ask Digital Agency, Ss Omnia, Sector 86, Gurugram, Haryana 122004.</li>
    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
    <li><strong>Country</strong> refers to: Haryana, India</li>
    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
    <li><strong>Service</strong> refers to the Website.</li>
    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
    <li><strong>Website</strong> refers to Ask Digital Agency, accessible from <a href="https://www.askdigitalagency.com" target="_blank">https://www.askdigitalagency.com</a></li>
    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
</ul>

    </div>

   <div class="section">
    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    
    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
    </ul>
    
    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
</div>

    <div class="section">
    <h2>Tracking Technologies and Cookies</h2>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    
    <ul>
        <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
        <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
    </ul>

    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.</p>

    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

    <ul>
        <li><strong>Necessary / Essential Cookies</strong><br>
            <strong>Type:</strong> Session Cookies<br>
            <strong>Administered by:</strong> Us<br>
            <strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
        </li>

        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br>
            <strong>Type:</strong> Persistent Cookies<br>
            <strong>Administered by:</strong> Us<br>
            <strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.
        </li>

        <li><strong>Functionality Cookies</strong><br>
            <strong>Type:</strong> Persistent Cookies<br>
            <strong>Administered by:</strong> Us<br>
            <strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
        </li>
    </ul>

    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
</div>




<div class="section">
    <h2>Use of Your Personal Data</h2>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
        <li>For the performance of a contract: to fulfill purchase contracts and other agreements with Us.</li>
        <li>To contact You: via email, phone, SMS, or notifications for updates or information.</li>
        <li>To provide You with news, special offers, and general information unless opted out.</li>
        <li>To manage Your requests to Us.</li>
        <li>For business transfers: in case of a merger, acquisition, or sale of the Company.</li>
        <li>For other purposes: such as analytics, trends, promotional effectiveness, and improvement of the Service.</li>
    </ul>
</div>

<div class="section">
    <h2>Sharing Your Personal Information</h2>
    <ul>
        <li><strong>With Service Providers:</strong> For monitoring and communication purposes.</li>
        <li><strong>For Business Transfers:</strong> In the event of negotiations or execution of business mergers/sales.</li>
        <li><strong>With Affiliates:</strong> With entities under common control or ownership with appropriate privacy safeguards.</li>
        <li><strong>With Business Partners:</strong> To offer you related products or services.</li>
        <li><strong>With Other Users:</strong> If you interact publicly on the platform, your data may be visible to others.</li>
        <li><strong>With Your Consent:</strong> For any other purpose that you consent to.</li>
    </ul>
</div>

<div class="section">
    <h2>Retention of Your Personal Data</h2>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
</p>
</div>

<div class="section">
    <h2>Transfer of Your Personal Data</h2>
    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
</p>
</div>

<div class="section">
    <h2>Delete Your Personal Data</h2>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
Our Service may give You the ability to delete certain information about You from within the Service.
You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
</p>
</div>

<div class="section">
    <h2>Disclosure of Your Personal Data</h2>
    <h3>Business Transactions</h3>
    <p>If involved in a merger or acquisition, your data may be transferred. You will be notified beforehand.</p>
    
    <h3>Law Enforcement</h3>
    <p>Your data may be disclosed if required by law or legal process.</p>
    
    <h3>Other Legal Requirements</h3>
    <p>Your data may also be disclosed to:</p>
    <ul>
        <li>Comply with legal obligations</li>
        <li>Protect and defend Company rights</li>
        <li>Investigate Service-related wrongdoing</li>
        <li>Protect user or public safety</li>
        <li>Defend against legal liability</li>
    </ul>
</div>

<div class="section">
    <h2>Security of Your Personal Data</h2>
    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
</div>

<div class="section">
    <h2>Children's Privacy</h2>
    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
</p>
</div>

<div class="section">
    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
</p>
</div>


    <div class="section">
        <h2>Changes to This Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
</p>
    </div>

    <div class="section contact-info">
        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy:</p>
        <p>Email: <strong>agency@askdigitalagency.com</strong></p>
    </div>

@include('front-end.footer')
